-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.city
(
    city character varying COLLATE pg_catalog."default" NOT NULL,
    county character varying COLLATE pg_catalog."default" NOT NULL,
    year integer NOT NULL,
    population numeric,
    CONSTRAINT pk_city PRIMARY KEY (city, county, year)
);

CREATE TABLE IF NOT EXISTS public.license
(
    license_id character varying COLLATE pg_catalog."default" NOT NULL,
    store_id integer,
    license_cost numeric,
    CONSTRAINT pk_license_id PRIMARY KEY (license_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    date date,
    store_id integer,
    vendor_id integer,
    product_id integer,
    order_qty numeric,
    order_cost numeric,
    order_liters numeric,
    CONSTRAINT temp_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.price
(
    product_id integer NOT NULL,
    date date NOT NULL,
    pack_size numeric,
    bottle_ml numeric,
    state_bottle_cost numeric,
    state_bottle_price numeric,
    CONSTRAINT pk_product_id_date PRIMARY KEY (product_id, date)
);

CREATE TABLE IF NOT EXISTS public.product
(
    product_id integer NOT NULL,
    product character varying COLLATE pg_catalog."default",
    vendor_id integer,
    category character varying COLLATE pg_catalog."default",
    category_group character varying COLLATE pg_catalog."default",
    CONSTRAINT product_distinct_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.store
(
    store_id integer NOT NULL,
    store character varying COLLATE pg_catalog."default",
    status character varying(1) COLLATE pg_catalog."default",
    address character varying COLLATE pg_catalog."default",
    city character varying COLLATE pg_catalog."default",
    zip_code integer,
    county character varying COLLATE pg_catalog."default",
    latitude numeric(10, 7),
    longitude numeric(10, 7),
    store_type character varying COLLATE pg_catalog."default",
    retail_sqft numeric,
    CONSTRAINT store_pkey PRIMARY KEY (store_id)
);

CREATE TABLE IF NOT EXISTS public.vendor
(
    vendor_id integer NOT NULL,
    vendor character varying COLLATE pg_catalog."default",
    CONSTRAINT vendorss_pkey PRIMARY KEY (vendor_id)
);

ALTER TABLE IF EXISTS public.license
    ADD CONSTRAINT fk_store_id FOREIGN KEY (store_id)
    REFERENCES public.store (store_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk_product_id FOREIGN KEY (product_id)
    REFERENCES public.product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk_product_id_date FOREIGN KEY (date, product_id)
    REFERENCES public.price (date, product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk_store_id FOREIGN KEY (store_id)
    REFERENCES public.store (store_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk_vendor_id FOREIGN KEY (vendor_id)
    REFERENCES public.vendor (vendor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT fk_vendor_id FOREIGN KEY (vendor_id)
    REFERENCES public.vendor (vendor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;